/*
 * ReCiter API
 * ReCiter API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jie265@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Identity;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for IdentityApi
 */
@Ignore
public class IdentityApiTest {

    private final IdentityApi api = new IdentityApi();

    
    /**
     * Add a new Identity
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addIdentityTest() throws ApiException {
        Identity body = null;
        api.addIdentity(body);

        // TODO: test validations
    }
    
    /**
     * Deletes an Identity
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteIdentityTest() throws ApiException {
        Long uid = null;
        api.deleteIdentity(uid);

        // TODO: test validations
    }
    
    /**
     * Find Identity by ID
     *
     * Returns a single Identity
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getIdentityyIdTest() throws ApiException {
        Long uid = null;
        Identity response = api.getIdentityyId(uid);

        // TODO: test validations
    }
    
    /**
     * Update an existing Identity
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateIdentityTest() throws ApiException {
        Identity body = null;
        api.updateIdentity(body);

        // TODO: test validations
    }
    
}
